### ISSUE TITLE
[Bug] "Display Lookup Table Roll" not working

### ISSUE THREAD

**Issue by sub-atomic** [javalent/dice-roller#103]
I've been having trouble with Dice Roller displaying the lookup table rolled number. I thought it might be a conflict with a theme or css snippet, so I opened the sandbox vault, installed Dice Roller, with "Display Lookup Table Roll" enabled, and created two notes: "Roller.md" and "Lookup.md".

In "Roller.md", I have:

`dice: [[Lookup^Table]]`

In "Lookup.md", I have:

```
| dice: 1d6 | Result |
|---|---|
| 1 | a |
| 2 | b |
| 3 | c |
| 4 | d |
| 5 | e |
| 6 | f |

^Table
```
When I switch to reading mode, the dice result and dice button are visible in "Roller.md", but there is no lookup table rolled result. If I change the heading of the first column of the lookup table to `roll: 1d6` instead of `dice: 1d6` then the lookup table roll displays properly in front of the result, but only if "Display Lookup Table Roll" is turned off. 

Not sure if I'm doing something wrong, or what. Hope this helps to iron out a bug.

**Comment by ars-dev-br** [comment]
Have you tried removing the blank line between the table and `^Table`?

**Comment by Feldherren** [comment]
Even without the blank line between the table and its name, the option to Display Lookup Table Roll doesn't seem to do anything.

**Comment by sigrunixia** [comment]
Confirming this bug is still apparent, @valentine195. No errors in console.
