### ISSUE TITLE
dice-mod glitches out and fails to replace text when having multiple while switching to reading mode

### ISSUE THREAD

**Issue by Darkrael** [javalent/dice-roller#126]
When using multiple "dice-mod" fields on the same document and switching to reading mode to roll them, the engine seems to glitch out and randomly misses replacing fields as shown in the following video:

https://user-images.githubusercontent.com/42981119/173448344-52da2c08-0866-470e-9918-08d2e4a06307.mp4

**Comment by xgdgsc** [comment]
When using multiple dice-mod inside the daily template, it seems to fail for last mods. Ending up with corrupt texts.

**Comment by xgdgsc** [comment]
https://forum.obsidian.md/t/data-race-safe-way-of-modifying-files/30847
