### ISSUE TITLE
Feature Request: FUDGE/Fate Dice Table Rolls Lookup

### ISSUE THREAD

**Issue by Breganov** [javalent/dice-roller#134]
All the negative results seems to be getting randomized at some point. I think that `-` symbol parsed as a part of `n-m` syntax, where `n` and `m` are the numbers of the the results and not an actual negative number. So I think the rule makes think that it's rolling from None to `-4` for example if I placed -4 as a valid table line.

I wish we could use it because it's giving a way to roll lots of Mindjammer tables. They are all strictly used with Fate dice. And it's impossible to roll one without the other.

**Comment by sigrunixia** [comment]
@Breganov 
Hello, I am helping @valentine195 get caught up on the issues here. 

Do you still have this issue, and if so, can you provide a several different examples in the form of markdown notes for me to test? Unfortunately, I am not as familiar with the Fudge/Fate system as I ought to be.
