### ISSUE TITLE
Feature Request: Display results of individual rolls when rolling multiple dice in sidebar

### ISSUE THREAD

**Issue by eyriewow** [javalent/dice-roller#140]
Issue:

In the German TTRPG "Das Schwarze Auge" (The Dark Eye) a skill check requires the use of 3 d20 where each individual roll is used to check a specific attribute required for that skill. For example a check for intimidation would roll 1d20 for courage, intelligence and charisma. 
The current behavior in the sidebar is to display the sum of all rolls and only displaying the formula that lists the individual rolls when hovering over the result which is a bit cumbersome when the individual rolls matter.

Proposed solutions:

- comma separated individual rolls: `dice: 1d20,1d20,1d20`
- enabling the `|form` flag in the sidebar

Either would solve my personal use case but I feel the second solution is a bit more elegant as well as being expected behavior from dice rolls within notes.

**Comment by danreuben** [comment]
This would be helpful for evaluating dice rolls in any dice pool game. With the help of your plugin I have mostly converted an Ironsworn coop game over to Obsidian from Discord.

The primary action roll in Ironsworn is a pool of 1d6 and 2d10. The d6 result is evaluated against each d10 result to determine the level of success or failure. Matching d10 results trigger a twist in the effect as well. Having the individual results show in dice view with the option to copy would be fantastic. We keep a log of each roll embedded along with the narrative outcome.

The option to auto copy the last roll to the clipboard would make it amazing. Especially in conjunction with what I believe you call section rolls. We use the text labeled formula buttons embedded onto our character sheets.

Thanks for the plugin and reading our requests.

**Comment by sigrunixia** [comment]
@eyriewow I am sure if you are aware, but |form and other formula options are now enabled.

<img width="544" alt="image" src="https://user-images.githubusercontent.com/68425372/233497043-85da63ed-fea3-493d-a8d3-67367c1a7a05.png">

@danreuben Could you make a new issue for the request to auto copy last roll setting?

**Comment by sigrunixia** [comment]
Closing as the primary request appears to have been achieved. If it has not, a new feature request can be created.
