### ISSUE TITLE
FEAT: Pipe dice sections/notes results 

### ISSUE THREAD

**Issue by pikatwinky** [javalent/dice-roller#148]
I think your plugin is amazing, but i'm wondering if could be posible, when using the capability of retrieve notes, sections, lines, etc (btw i think this is a really powerfull feature, thank you so much), to chain (to pipe, to concat?) the results of a dice roller with another one?

One example could be, if I had a note named 'clothes' with the list of all my clothes (a list of links to notes representing the categories: shirts, socks, shoes, etc), and inside one of these notes there is a list of all my clothes inside that category. For example i'd had [[clothes]]>[[shirts]]>list_elements('blue_shirt')

At the moment i have to write a query for the first random selection
`dice:[[clothes]] | line` //Retrieves one note representing a category shirts, socks, shoes, etc

and then write this item retrieved manually in the next query, lets say it was 'shirts'

`dice:[[shirts]] | line` // return my desired shirt item

It could be awesome to be able to pass the first query as argument of the second  one 
`dice: [[ (dice:[[clothes]] | line )    ]] | line`  
 
or to pipe both queries maybe with an operator

`dice:[[clothes]] | line` > `dice:[[previous_result]] | line`

This applications allows me to choose randomly what combination should i wear today, but i think it could be really useful for another kind of applications as well, i use this also to choose the next movie to watch.

Is there a workaround to achieve this at this moment by chance?

Thanks in advance

**Comment by Janrith** [comment]
You can definitely nest table rolls:

Using the movies example, the docs say you can have, say, a table of genres, then for each result at that top level, have that roll on another table as the result:

\`dice: [[AdHoc Scripting^movieGenres]]\`

\#\# Movie Genres
\| dice: d20 | Genre                                     |
\|:---------:| ----------------------------------------- |
\|    1-5    | \`dice: [[AdHoc Scripting^genreAction]]\`  |
\|   6-10    | \`dice: [[AdHoc Scripting^genreComedy]]\`  |
\|   11-15   | \`dice: [[AdHoc Scripting^genreRomance]]\` |
\|   16-20   | \`dice: [[AdHoc Scripting^genreHorror]]\`  |
^movieGenres

\#\# Action

\| dice: d4 | Movie                  |
\|:--------:| ---------------------- |
\|    1     | The Other Guys         |
\|    2     | Mission Impossible     |
\|    3     | Uncharted              |
\|    4     | Raider of the Lost Ark |
^genreAction

\#\# Comedy
\| dice: d3 | Movie                  |
\|:--------:| ---------------------- |
\|    1     | Thor: Love and Thunder |
\|    2     | We're the Millers      |
\|    3     | Date Night             |
^genreComedy

\#\# Romance
\| dice: d3 | Movie          |
\|:--------:| -------------- |
\|    1     | 50 First Dates |
\|    2     | Must Love Dogs |
\|    3     | Serendipity    |
^genreRomance

\#\# Horror
\| dice: d3 | Movie           |
\|:--------:| --------------- |
\|    1     | Halloween       |
\|    2     | Drag Me to Hell |
\|    3     | Alien           |
^genreHorror

Note the difference in block_id syntax from standard link notation (Note^block_id vs. Note#^block_id).
