### ISSUE TITLE
Feature Request: Rolling Dice looking into the second/third column

### ISSUE THREAD

**Issue by Fjalk** [javalent/dice-roller#149]
Currently, when rolling the dice, the first column is looked at. Is it possible to roll the dice in such a way that the dice are also rolled from the second or third column?

This would be important for the following tables:

Terminus | Outlands | Expanse | Result
:-------:|:--------:|:-------:|------------------------
1–50     | 1–75     | 1–90    | None
51–70    | 76–87    | 91–96   | Orbital settlement
71–85    | 88–95    | 97–100  | Planetside settlement
86–95    | 96–98    | --      | Multiple settlements
96–100   | 99–100   | --      | Settlements in conflict

Thank you in advance for the answer and the effort.

Fjalk

**Comment by sigrunixia** [comment]
Tagging as feature respect. 

They are specifically looking for multi header support with the ability to also negate headers.
