### ISSUE TITLE
Table Roller doesn't allow literal values to be passed into it.

### ISSUE THREAD

**Issue by Janrith** [javalent/dice-roller#151]
Hey there,

Unless I'm missing something fundamental, the syntax for the current Table Roller implementation isn't allowing literal values (12, 15, 6, etc.) to be passed into it.

Reading the doc, it notes the following syntax:

`dice: X[[Note^block-id]]`

This seems to imply passing an integer value for X should return row X from the table.  However, when I try, I get an error message.

Here's my syntax:

`dice: 3[[ChTableTest^charismaTable]]|Max Henchmen`

and the target table:

![image](https://user-images.githubusercontent.com/116475084/200447783-1ee1a17c-57b1-4fff-96e9-266562b6ce86.png)

And here's the result.

![image](https://user-images.githubusercontent.com/116475084/200447476-75e296ae-71fd-4a00-ac30-35ba57fb666c.png).

If I omit the leading number, it rolls randomly on the table.

I'd like it to lookup the correct row (ideally based on the data in the first column rather than a literal row number) and allow me to retrieve the data points requested by the Header suffix.

Am I doing something wrong here?

**Comment by Janrith** [comment]
Ideally, I'd like to use Frontmatter data for the lookup, i.e.:

\` dice: this.Charisma[[ChTableTest^charismaTable]]|Max Henchmen\`

**Comment by ars-dev-br** [comment]
That's not my understanding of what's in the documentation:

> To return **multiple elements**, use a [dice formula](https://github.com/valentine195/obsidian-dice-roller#dice-rollers) before the wikilink:

That is, `dice: 3[[ChTableTest]]` will return three random rows from `ChTableTest`.
