### ISSUE TITLE
[BUG] Rendered Dice show different Result then showed in Note

### ISSUE THREAD

**Issue by ImmoNilsEckelt** [javalent/dice-roller#152]
First roll of inline `dice: 2d20kh` renders differently than what is printed out.

<img width="616" alt="Bildschirm­foto 2022-11-09 um 16 31 14" src="https://user-images.githubusercontent.com/89914350/200872297-ac4d6773-3ac4-4de3-81fe-edda3873b58f.png">
Prints out 3 but has rolled [14d, 20]. Only first roll after opening the note, second try works again.

**Comment by sigrunixia** [comment]
This appears to be resolved as I am unable to duplicate it. If there is still an issue, a new issue thread can be created.

**Comment by ImmoNilsEckelt** [comment]
I still experience the same issue. It there is a difference between the three places where the result is shown. rendered dice: 20. Top-right: 20. Text in obsidian, the only one that stays, btw, 3. 
But only with the first throw of a dice-set. 

I can reproduce by adding these lines:

`dice: 1d6`    
`dice: 3d20k` 

Click upper one, should show difference between rendered and what is shown in the text-document. switch to the lower one, same. It is not happening though, when you use the same dice twice or more times. It's only the first time it is been used.

**Comment by sigrunixia** [comment]
We'll continue this in #196. The version/file numbers have massively changed since the original issue, and this will help debugging.
