### ISSUE TITLE
[Bug] Using a Min/Max formula in the Sidebar dice roller is treated as d[Max], ignoring Min.

### ISSUE THREAD

**Issue by Janrith** [javalent/dice-roller#155]
As the title suggests, rolling a min/max formula (such as 4d[4,8]+4) in the right sidebar UI seems to be ignoring the min value provided.

![image](https://user-images.githubusercontent.com/116475084/206340842-955853e7-6578-493d-bcf1-b3e090c4a77b.png)

However, the same formula functions correctly inline.

![image](https://user-images.githubusercontent.com/116475084/206340911-f2a4cfa5-b283-4209-8082-20c63b45d339.png)

**Comment by sigrunixia** [comment]
This appears to have been fixed. Closing. If this issue is still a problem for a user, please create a new issue thread.
