### ISSUE TITLE
dddice

### ISSUE THREAD

**Issue by patrickporto** [javalent/dice-roller#162]
I wonder if it is possible to integrate with [dddice](https://dddice.com).  In case doesn't possible, how to another plugin could catch your plugin events?

**Comment by valentine195** [comment]
I was looking at their website and it seems like it would be straightforward enough to add some sort of integration. 

What would you like to see- rolls just roll in a dddice room?

**Comment by patrickporto** [comment]
Yes, just that

**Comment by sigrunixia** [comment]
[Link to API](https://docs.dddice.com/api/?ref=footer#introduction)

Tagging also as great first issue in case someone else wants to ply their hand at it.
