### ISSUE TITLE
[Feature request] Option to recognize XWX as XdX

### ISSUE THREAD

**Issue by Inoshiro90** [javalent/dice-roller#163]
Hello,
I am playing with the German version of Dungeons and Dragons. Instead of XdX we have XWX (W stands for "Würfel" which translates as dice). This means that I always have the format XWX (1W20, 2W4, 3W8 etc.) instead of XdX (1d20, 2d4, 3d8 etc.) in my documents. 

Is it possible to add the option that XWX formats can also be recognised as XdX formats? Because so far they are not recognised by DiceRoller.

Love the plugin btw.

Best regards
Simon

**Comment by sigrunixia** [comment]
Adding tag as enhancement and critical as this is related to accessibility, language, and inclusion.
