### ISSUE TITLE
[BUG] Cannot use metadata/fields that start with the "dice modifier letters".

### ISSUE THREAD

**Issue by BruteThought** [javalent/dice-roller#165]
When attempting to use dice formula using tags/fields that start with the letter "r", it doesn't work, and will remain as text.
e.g. `dice: 1d10 + ref`

I believe it has to do with [this section](https://github.com/valentine195/obsidian-dice-roller/blob/240f4293c73e0f138f4b9a475ed620f84f2bba00/src/parser/lexer.ts#L56), as after further testing, using a tag starting with the letter "k" or "dh" causes the same issue. 

It may be attempting to interpret tags starting with these letters as dice modifiers.

**Comment by sigrunixia** [comment]
I am unable to reproduce this on my end. Are you still having this issue @BruteThought?

**Comment by BruteThought** [comment]
Yes, I have included an example note below:
```
---
abc: 5
def: 100
ref: 2000
---


`dice: 1d1 + abc`
`dice: 1d1 + def`
`dice: 1d1 + ref`
```

If you load the note as is, the dice will not load, however, if you remove the line:
```
`dice: 1d1 + ref`
```
All instances will load correctly (with results of 6 and 101 respectively).
Renaming the "ref" variable to variables starting with "k" or "dh", will also cause a similar issue. Testing it with other "valid" names, such as "gggg" will cause it to load as normal, with a result of 2001.
