### ISSUE TITLE
[Feature Request] The Table roller roll with another dice formula

### ISSUE THREAD

**Issue by Zagor91** [javalent/dice-roller#168]
With the table:
| dice: 1d4 | Result |
| 1 | option 1 |
| 2 | option 2 |
| 3 | option 3 |
| 4 | option 4 |
^test

This formula dice: [[ThisNote^test]] reviews either "option 1", "option 2", "option 3" or "option 4"

But the formula dice: 1d1+1[[ThisNote^test]] returns multiple elements, for example: "option 2||option 4"

I want to return from the table ThisNote^test not the result of the dice: 1d4 but another die roll: 1d2, for exemple with dice: [[ThisNote^test]]|dice:1d2 must return "option 1" or "option 2" but not option 3 or 4.

**Comment by sigrunixia** [comment]
This feature is looking to add a conditional on multi row table roller.

Related:
#172 
#175 
#179
