### ISSUE TITLE
Feature Request: Combine multiple table rolls into a single result

### ISSUE THREAD

**Issue by paddirn** [javalent/dice-roller#174]
Unless I'm missing something, it would be great to be able to combine the results of multiple table rolls together into a single string result, as it would make it easier for creating Oracle rollers for narrative games like Ironsworn. It could also help with things like NPC generation, where you might want to roll across a half-dozen tables to generate a random slate of characteristics for a character.

Possible format might be something like: `dice: [[Oracles.md#^action]] + " " + [[Oracles.md#^theme]]` which would generate a roll across each table with a space between them.

**Comment by OberstK** [comment]
dumb question: Why arent you making this two separate inline rolls? Achieves the same result and thats how I do it for NPCs for example.

`dice: [[Oracles.md#^action]]` `dice: [[Oracles.md#^theme]]`

**Comment by paddirn** [comment]
Mostly just out of laziness. The result I'm hoping to achieve is one click that rolls multiple items at once. Independently I've been able to achieve it using the Buttons plugin and just assigning it to reroll everything on the page, though it would be nice to selectively do it and only re-roll a group of items at a time.

**Comment by sigrunixia** [comment]
Tagging as feature.
