### ISSUE TITLE
[Feature Request] Exclude specific note from random result

### ISSUE THREAD

**Issue by QuantumBob** [javalent/dice-roller#175]
You have written a great set of plugins for obsidian.
I have been using the dice roller and was wondering if there was a way to exclude a note from a random result when using tags.
I have a npc template with a tag "#npc" that gets added to all my npc characters. In various tables I reference the tag to pick a random npc ie `dice: #npc\|link`. 
It works but sometimes it picks the npc template note.
So is there a way to exclude the template note or is it something that could be added in future versions?
Thanks in advance.

**Comment by tauren** [comment]
👍 I came here to make the same request, also related to the tag being within a template file.

**Comment by sigrunixia** [comment]
Tagging as feature.

Another thought is adding not conditionals.

**Comment by tauren** [comment]
Did this get implemented or was the issue auto-closed?
