### ISSUE TITLE
[Feature Request] Support dataview [key::value] as Number of dice (= support for Mage-like rule-sets)

### ISSUE THREAD

**Issue by EtienneSafa** [javalent/dice-roller#176]
Being able to add a dataview value to a roll is dope! Thanks for that!
➡ `dice: 1d20 + strength`
✅ works great for DnD-like rule-sets (where you add a characteristic to a dice roll)

**How Mage-like rule-sets works :**
🎲  `dice: 5d10>5sd`
 ➡ typical Mage dice roll saying "I fight : let's roll my [Strength + Blade = 2 + 3 = 5] d10 and see how many sucesses I have"

**What I'd love to be able to do w/ Dice Roller:**
🎲  `dice: [strength]d10>5sd`
🎲  `dice: [strength + blade]d10>5sd`

➡ so that I could just have my character's characteristics stored in metadata or inline with `strength::2` and `blade::3`, change those and don't need to edit the dice roll lines :)

**Comment by sigrunixia** [comment]
This extends an existing feature of Dataview Inline metadata. Tagging as feature. 

This could have much further reaching applications than just dataview inline if implemented, @valentine195.
