### ISSUE TITLE
Non-modifying mode where output is displayed in some other way

### ISSUE THREAD

**Issue by lhannest** [javalent/dice-roller#178]
> This plugin comes with no guarantee of stability and bugs may delete data. Please ensure you have automated backups.

It would be nice to have a mode that completely disables the note-modifying feature of this plugin and provides an alternate output for rolls.

For example, the "Results" section of the Dice View sidebar should show the results of clicking any `dice: ...` text, and not just the results of calculations performed within the side bar.

**Comment by valentine195** [comment]
Hi, the only modifications happening to note content is if you explicitly use `dice-mod`. That is a generic catch all warning.

**Comment by valentine195** [comment]
Having said that, having a results section that displays all results is a good idea, but it would probably be its own view.
