### ISSUE TITLE
Feature Request: Ability to use parameters with type

### ISSUE THREAD

**Issue by KareemMukbil** [javalent/dice-roller#179]
For instance, 
`dice: [tag here]|+blockquote`
would return a single random *blockquote* from every note with the tag.
And,
`dice: [tag here]|-blockquote`
would return a random *blockquote* from a single random note with the tag.

---
Alternatively, a way to enable **"Roll All Files for Tags"** on some notes while leaving it disabled on others.

**Comment by sigrunixia** [comment]
Tagging as feature.

A not conditional here would also solve #175.

**Comment by valentine195** [comment]
Hey, you can do this already. You just need a pipe after the tag.
