### ISSUE TITLE
Rendering double results 

### ISSUE THREAD

**Issue by jethoof** [javalent/dice-roller#197]
![image](https://user-images.githubusercontent.com/102444466/233744658-0a69533f-f1aa-4236-997a-4bad9505d5c6.png)

This occurs during the initial load of the file and disappears once clicked to reroll.

**Comment by sigrunixia** [comment]
I am getting similar, strange results when I attempt to duplicate within callouts and embeds. 

This can be tested by enable and disabling the formula setting within Dice Roller Settings. Live preview will update on the next dice roll but callouts version may update, and then revert, and then update again.

**Comment by sigrunixia** [comment]
> ![image](https://user-images.githubusercontent.com/102444466/233744658-0a69533f-f1aa-4236-997a-4bad9505d5c6.png)
> 
> This occurs during the initial load of the file and disappears once clicked to reroll.

@jethoof Are you still experiencing variances in dice rolling between callout and non-callout rolls?

**Comment by jethoof** [comment]
It's been fixed! What was the cause of it?

**Comment by valentine195** [comment]
I have no idea lol

**Comment by sigrunixia** [comment]
I suspect as we have insider build access, something going on there. I'll go ahead and resolve this thread! <3
