### ISSUE TITLE
The documentation of "Usage in Other plugins" is unclear, it requires some digging in the code to get anywhere

### ISSUE THREAD

**Issue by rolandhesz** [javalent/dice-roller#210]
### What are we changing or adding?

- [ ] Repository
- [X] [Publish Documentation](https://plugins.javalent.com/)

### Location

Usage in Other plugins

### The issue is...

So I have tried to write a little code to use the dice roller with some data.

The first step was to use the provided example and see how the result of the roll is generated.
The available documentation got me to the point where the `diceRoller` is created.

```dataviewjs
const diceRollerPlugin = app.plugins.getPlugin("obsidian-dice-roller");
const diceRoller = await diceRollerPlugin.getRoller("1d3+3d8");
```

The `diceRoller` has a value, but it clearly doesn't contain any result in it.
There is an additional step, but it is missing from the documentation explaining how to use the plugin from code, and while it is probably "as obvious as it can be", still, it would be great if the example included it. 

### Suggestions?

Can you add to the example the line that actually gets the result from the roller? 
Something like the following:

------

## Usage in Other plugins

Plugins that have the ability to write JavaScript (such as DataView) can interface with the Dice Roller plugin in by accessing it on the Obsidian app object:

`const diceRollerPlugin = app.plugins.getPlugin("obsidian-dice-roller");`

Once you have an instance of the plugin, you can then generate the various types of rollers, such as a dice roller, tag roller, etc, using the `getRoller` method:

```
//definition
getRoller(diceString: string, sourceFile: string = ""): Promise<Roller>;

//example
const diceRoller = await diceRollerPlugin.getRoller("1d3+3d8");
```

To make a roll, using the `diceRoller` object, call the `roll()` function.
This will return the result of the roll and store it in the `diceRoller.result` field, meaning the result can be accessed like this:

```
let diceRoll = await diceRoller.roll();
```
and like this:

```
await dicerRoller.roll();
...
let diceRoll = diceRoller.result;
```

### Anything else?

Nothing really, the plugin is great, looking forward to seeing how it gets better over time. :)

**Comment by sigrunixia** [comment]
Thanks for the request to update. It still feels like I am a long way to getting this documentation all up to date, so this was super helpful in pointing out a blind spot. 

This _should_ be resolved in [Dice and Javascript](https://plugins.javalent.com/dice/javascript) (Did some restructuring). 

Can you check this and see if it meets the parameters of your request?
