### ISSUE TITLE
[Basic Usage]: Table Roller doesn't work/is confusing to use

### ISSUE THREAD

**Issue by Nivyan** [javalent/dice-roller#225]
### Check for existing bug reports before submitting.

- [X] I searched for existing [Bug Reports](https://github.com/javalent/dice-roller/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-descc) and found no similar reports.

### Expected Behavior

I've copy-pasted multiple examples from the documentation directly into my markdown, yet it doesn't render.

The [documentation](https://plugins.javalent.com/dice/rollers/table) or [documentation for lists](https://plugins.javalent.com/dice/rollers/list), both says to simply make a table/list and reference it in a codeblock. Like so:

```
| Header |
| A          |
| B          |
```

Or

```
-   a
-   b
-   c
-   d
```

And then reference it in another note like so:

`dice: [[Note^block-id]]`

### Current behaviour

A simple roll like so:  
`dice: 1d4`
...works as intended.

But any kind of reference simply loads the entire file, and the dice graphic does nothing when clicked.

[Image](https://i.imgur.com/otf99Hg.png)

I've now tried simply copy pasting the _exact_ examples in the documentation, but [it doesn't render anything from the note at all](https://i.imgur.com/S6VJkEj.png).

### Reproduction

Copy and paste the [documentation](https://plugins.javalent.com/dice/rollers/list) [examples](https://plugins.javalent.com/dice/rollers/table), and notice that they fail or doesn't work as intended.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.3.5

### Plugin Version

8.17.0

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by sigrunixia** [comment]
Can I have some clarification on if you are copying and pasting, or manually typing in the examples?

**Comment by Nivyan** [comment]
> Can I have some clarification on if you are copying and pasting, or manually typing in the examples?

Yes.

I tried manually first, because it seemed incredibly simple. Then I tried manually following the documentation, then I copy-pasted when I got too frustrated.

**Comment by Nivyan** [comment]
I figured out the issue!

The documentation said that block references were optional. So to test and avoid as many variables, I tested with a single list or table in a note, and tried getting it without quoting.
