### ISSUE TITLE
[Bug]: Rolling graphical dice ignores advantage and disadvantage

### ISSUE THREAD

**Issue by Hapadbeep24** [javalent/dice-roller#227]
### Check for existing bug reports before submitting.

- [X] I searched for existing [Bug Reports](https://github.com/javalent/dice-roller/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-descc) and found no similar reports.

### Expected Behavior

When rolling 2d20dh it should roll 2 d20 dice and drop the lowest value. Same with kh keeping the highest value.

### Current behaviour

When rolling graphical dice, the advantage and disadvantage is ignored, and the dice roller adds the two rolls together regardless.

### Reproduction

1. Launch obsidian sandbox
2. Install dice roller plugin
3. Turn on "Display Formula With Results"
4. Turn on "Display graphics for Dice View Rolls"
5. Using the sidebar tool for dice roller, add 2 of the same dice, click "Adv" or "Dis" and roll
6. With graphics on, the formula will display the two rolls and the sum
7. With graphics off, the formula will display the two rolls and {n}d or {n}k depending on adv or dis

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Obsidian Version Check

1.3.5

### Plugin Version

9.0.0

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by hellquist** [comment]
FWIW I have the same, on all platforms I've tried (Win, macOS, iOS and iPadOS in my case). Came here to see if it was filed already, and here we are.

**Comment by valentine195** [comment]
This is fixed
