### ISSUE TITLE
Add a setting to enable a FATE dice icon

### ISSUE THREAD

**Issue by saif-ellafi** [javalent/dice-roller#251]
### Scope

Currently, to roll FATE dice one needs to manually enter the formula. Would be fantastic to be able to add an icon in the right-side pannel to quickly stack up fate dice (or simply add 4dF with one click, and quick-roll with right-click).

Currently, I have a second best mode which is having the formulas saved:
![image](https://github.com/javalent/dice-roller/assets/27952699/a1ee3966-6281-4943-9b2d-15623ff78b3b)

Thank you for the amazing plugin

### Discovery

Add a setting (default off): "Show Fate dice icon" - which adds it to the sidebar

### Validate

Latest version

**Comment by valentine195** [comment]
Hey, I just wanted to let you know that I removed this button, but added a new feature that lets you specify your own buttons.

**Comment by saif-ellafi** [comment]
Awesome, thank you @valentine195 - But I think there is an issue now: The modifiers `+` and `-` modifiers do not add to the formula, and the right-click immediate dice-roll stoped working.
