### ISSUE TITLE
🐞 Graphical dice not accurate with actual roll

### ISSUE THREAD

**Issue by CobaltKyro** [javalent/dice-roller#252]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

When I go to roll the die with graphical dice enabled, the numbers for both the graphic itself and the recorded number should be the same.

### Current behaviour

When I roll a die with graphical dice enabled, the numbers are different between the number the graphical die lands on and the number that actually gets recorded on the Dice Roller panel.

### Reproduction

1. Turn on Graphical Dice in settings
2. Roll any number of Dice
3. Note the numbers on the graphic and the actual recorded roll, they are always different.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.4.16

### Plugin Version

10.0.2

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
Can you give me more details?

Are you rolling via the panel, or are the numbers in a note wrong?

Or is it just what is being recorded in the panel?

**Comment by CobaltKyro** [comment]
> Can you give me more details?
> 
> Are you rolling via the panel, or are the numbers in a note wrong?
> 
> Or is it just what is being recorded in the panel?

The panel I believe. Here is a screenshot.
![Screenshot 2023-10-15 142942](https://github.com/javalent/dice-roller/assets/45078054/06f62ff7-2bf2-44a1-b351-57bc6517897e)

**Comment by saif-ellafi** [comment]
Hi, I came to report this

**Comment by saif-ellafi** [comment]
I believe this started happening in one of the last patches
