### ISSUE TITLE
🐞  Dex modifier breaking the Initiative tracker with Dice roller on

### ISSUE THREAD

**Issue by f3ss1** [javalent/dice-roller#258]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

dice roller + fantasy statblocks + initiative tracker works fine for all creatures.

### Current behaviour

Enabling dice roller with the fantasy statblocks and initiative tracker ruins the start combat with creatures with DEX < 10.

### Reproduction

Install all the three mods, try to go to "Initiative tracker encounter builder" and add a creature like Zombie from the SRD. It won't work unless you disable the dice roller. 

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.4.16

### Plugin Version

10.1.2

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

### Possible solution

Probably the reason is the negative dex modifier to the initiative. However, simply setting the formula in initiative calculation to "4" did not work so it appears like the reason is somewhere deeper.

I found this while making custom mobs using YAML in fantasy statblock and debugged it up to this point. All the plugins are up to date to the current date.

**Comment by f3ss1** [comment]
UPD: it appears that I made a mistake while debugging and removing %mod% from the initiative formula indeed fixes the thing so I would look into the modifier.

**Comment by twiescha** [comment]
Just had a look in the debugger. The problem are negative modifiers. The diceroller needs to parse en expression like "1d20 + -2" in that case, which will result in the exact same error in calculate() when used in isolation as a formula in the dice tray.
 I think it basically treats it as ["1d20", "+", "-", "2"] instead of ["1d20", "+", "-2"]

**Comment by f3ss1** [comment]
@twiescha I bumped into something like this yesterday (the dicetray did not allow to make rolls, the button was unclickable) after doing something like 1d20 + 4 guess (but I am not sure on this one tbh so cannot reproduce).
