### ISSUE TITLE
save results don't seem to work with tag rollers

### ISSUE THREAD

**Issue by MathiasJon** [javalent/dice-roller#271]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

I checked Globally save results in options. All my other dice results (dice rolls/table rolls) are saved, and stay the same when i leave the note then come back. 

### Current behaviour

It is not the case for the tag roll: it is different each time I leave/come back to my note

### Reproduction

For example, with a tag "personne" linked to 3 notes, I have 3 different result each time I reload my note.

I used this formula: ``dice:#personne|link``

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.4.16 / 1.4.14

### Plugin Version

10.4.0

### Confirmation

- [ ] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
Saving results was removed in v11
