### ISSUE TITLE
Dice tray: selecting the d4 enters formula "1 * (2d8kh + 3)"

### ISSUE THREAD

**Issue by keithhannen** [javalent/dice-roller#276]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

In the dice tray, selecting the d4 should enter "1d4" in the formula box.

### Current behaviour

Selecting the d4 icon enters "1 * (2d8kh + 3)" in the formula box

### Reproduction

Select the d4 icon in the dice tra

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version Check

1.4.16

### Plugin Version

10.4.1

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by dtgay** [comment]
Close to same thing for me. My d4 button enters `1 * (2d8 + 3)`.
