### ISSUE TITLE
JavaScript section roller returns object not string

### ISSUE THREAD

**Issue by chmac** [javalent/dice-roller#283]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

I would expect that calling `roller.roll()` on a section roller should return a string, but it returns an object.

### Current behaviour

```ts
const diceRollerPlugin = app.plugins.getPlugin('obsidian-dice-roller')
const manifestoRoller = await diceRollerPlugin.getRoller('[[Quotes]]')
const section = await manifestoRoller.roll()
console.log(JSON.stringify(section))
```

This outputs a JSON object like so:

```
{
  "type": "paragraph",
  "position": {
    "start": {
      "line": 9,
      "col": 0,
      "offset": 66
    },
    "end": {
      "line": 10,
      "col": 10,
      "offset": 88
    }
  },
  "id": "dice-j5v2"
}
```

### Reproduction

Reproduction posted above.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version Check

1.4.16

### Plugin Version

10.4.0

### Confirmation

- [ ] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
This is expected behavior, but you can use `SectionRoller#displayFromCache(...cache: RollerCache[])` to get a string result.

**Comment by chmac** [comment]
@valentine195 Aha, thanks for sharing the way to resolve a string, I couldn't figure that out. 👍🏼
