### ISSUE TITLE
Javalent-Support-Thread doesn't seem to exist

### ISSUE THREAD

**Issue by chmac** [javalent/dice-roller#284]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

The new issue page says:

> Visit Javalent-Support-Thread to talk to a human and get some help.

I would expect that I can join the discord server and find a channel "Javalent-Support-Thread" that I could join.

### Current behaviour

Can't find the thread

### Reproduction

- Join discord
- cmd+k
- type "Javalent-Support-Thread"

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version Check

n/a

### Plugin Version

n/a

### Confirmation

- [ ] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
This is a thread in the official Obsidian discord.

**Comment by chmac** [comment]
Can you share how one can find it? It doesn't come up when I search in the official obsidian discord.

**Comment by valentine195** [comment]
It's a thread under the #tabletop-games channel. [Link](https://discord.com/channels/686053708261228577/932707309195493416)

**Comment by chmac** [comment]
Aha, I found it now with the link. Thanks. Do you think it would be possible to put that link on the GitHub issue creation form? Then people would be able to find it directly, might be easier. Or maybe update the description to say "in the tabletop-games channel"? I definitely wouldn't have thought to check that channel!
