### ISSUE TITLE
🐞 Dice-Mod folder suggester does not display

### ISSUE THREAD

**Issue by sigrunixia** [javalent/dice-roller#295]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

The folder suggester for excluding folders from dice-mod behavior should bring up the list of folders in the vault via the suggester.

### Current behaviour

The folder suggester only brings up `/` but no other 

### Reproduction

1. Start with a default obsidian setup.
2. Install Dice roller.
3. Enable dice roller.
4. Go to dice roller settings.
5. Toggle Dice-Mod.
6. Attempt to add template folders to Dice-Mod to ignore. 
7. See only the suggester provide `/`

Dice-Mod settings:
![CleanShot 2024-02-22 at 10 48 01](https://github.com/javalent/dice-roller/assets/68425372/8862d6dd-f2a4-47ac-99f0-45ffc7a0df66)

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version Check

1.5.8 and 1.5.8

### Plugin Version

10.4.4

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
This should be fixed in 10.4.5
