### ISSUE TITLE
✨ FR - choose the dice rolled to get data from a table

### ISSUE THREAD

**Issue by tyrcho** [javalent/dice-roller#299]
I'd like to control the dice rolled from the calling site and not only from the declaration site.

Exemples
* `dice: 1d8+4 [](page.md^bookmark)` would pull only in the last 8 items from a table of 12.
* `dice: 1d11 [](page.md^bookmark) dice: 1d11 [](page.md^bookmark)` would allow the 12th element of a table to roll twice on the other elements.

**Comment by matthewturk** [comment]
For what it's worth, I was able to make this work by executing:

```javascript
const roller = getRoller("[[Page^table]]");
await roller.getResult(); // to make sure lookupTable is created
roller.lookupRoller = getRoller("1d21 + 5")
```

`lookupRoller` doesn't get created until the first call to `getResult`, but after that it can be overridden.
