### ISSUE TITLE
🐞 Min/Max rolls result in only min or max Value

### ISSUE THREAD

**Issue by alkanex-xyz** [javalent/dice-roller#304]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

On testing Min/Max rolls the resultes should be in the rage of the provided min and max values

### Current behaviour

The result of Min/max rolls exclude all values between the provided range and result only in the Min or Max Value.
![Min_max](https://github.com/javalent/dice-roller/assets/62837071/f8549bfb-e7ce-48b4-82df-90efc9e161c1)

### Reproduction

I used this formular: `dice: 10d[5, 15]`

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.5.11

### Plugin Version

10.4.6

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by AustinYQM** [comment]
I believe I have fixed this in my PR.

![image](https://github.com/javalent/dice-roller/assets/5468703/632a01bb-c018-4cbf-b82c-9cfee5ad0a60)
