### ISSUE TITLE
🐞 Inline dice rolls using keep/drop formatting returns sum that includes all dice

### ISSUE THREAD

**Issue by morgan-gilbert** [javalent/dice-roller#305]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

I'm using a formula similar to this;
`dice-mod:3d6dl1 +1`. I expect the output to return a sum of the two highest dice +1. 

### Current behaviour

Currently, all dice are summed by the formula. That is, summing 3d6dl1 +1 will return a sum that includes all three dice. 

### Reproduction

Behavior should be reproducible using `dice-mod:3d6dl2 + 1` or similar code.  
![image](https://github.com/javalent/dice-roller/assets/51494577/dd1a3b16-5190-45e9-bd31-7c6f22453ffd)

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.28.7

### Plugin Version

3.6.3

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

### Possible solution

I'm not a coder, just an appreciator of this very versatile and useful mod.

**Comment by AustinYQM** [comment]
I can't recreate this locally. Here are some of my tests and results:

```
3d6dl2 + 1 -> [3d, 6, 4d] + 1 -> 7

2d6dl1 + 1 -> [4, 4d] + 1 -> 5

10d6dl2 + 1 -> [2, 2, 2, 4, 2, 2, 2d, 6, 5, 2d] + 1 -> 26
```

**Comment by valentine195** [comment]
I also cannot reproduce this.
