### ISSUE TITLE
🐞 Dice tray roll button only erases the formula and doesn't roll

### ISSUE THREAD

**Issue by d3Xrr** [javalent/dice-roller#317]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

When you enter formula or click a die picture inside a dice tray, it should roll and show result.

### Current behaviour

When I enter a formula into the dice tray and click roll, the formula just disappears, and nothing happens. There is no roll result or error message displayed.

https://github.com/javalent/dice-roller/assets/129934266/4fcedb13-e087-419c-835c-74b81af13872

### Reproduction

It doesn't work inside a new vault with plugins or sandbox vault either. 

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.5.12

### Plugin Version

11.0.3

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by FilBot3** [comment]
It happens on all platforms now. I've updated dice-roller a few times, and it now requires you configure it to actually make it work. It doesn't work out of the box anymore.

- Click GEAR icon for settings.
- Scroll down to your Dice Roller settings.
- Expand Dice Rollers
- Toggle Log Rolls to Dice Tray

Now it should be working.

I am also not real happy with these changes as I have other issues such as now the dice formulas in the dice tray are not rendering even when the toggle is switched. So there's something going on in this Obsidian plugin.

**Comment by d3Xrr** [comment]
Thank you for thorough instructions. That helped.
