### ISSUE TITLE
Table roller doesn't query note per roll 

### ISSUE THREAD

**Issue by Shyclops** [javalent/dice-roller#321]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

Table roller checks table on each roll 

### Current behaviour

Table roller seems to query and cache table, which ignores change

![image](https://github.com/javalent/dice-roller/assets/10409204/e1818f09-d12f-44c7-a314-c4c2a5bbedfa)

### Reproduction

Setup

have two notes, one with table 
| Test |
| --- |
| a |
| a |
| b |
| b |

the other with 
`dice: note1#^test-table`

roll the table once 

Steps
1. DO NOT CLOSE THE NOTE WITH THE DICE ROLLER
2. open the table note outside of obsidian (might work in obsidian, just not how i tested) and delete all table rows with b
3. roll the table again
4. repeat until table rolls "b" 

Notes:
This should work as long as the note with the table roller isn't refreshed, no matter how the table is edited 
I've tested this with both metabind regex edit as well as editing it in sublime 

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.6.2

### Plugin Version

11.0.4

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

### Possible solution

re parse the table every time the button is pressed, if performance is a concern, hash the table and compare the hash, if the hash is different, update the table and hash

**Comment by valentine195** [comment]
> if performance is a concern, hash the table and compare the hash, if the hash is different, update the table and hash

The reason this is done is to avoid re-reading the note content, not re-generating the options.

How often are you changing tables outside of Obsidian while using Dice Roller? I am inclined to close this, as it seems like a relatively obscure issue.

**Comment by valentine195** [comment]
This was fixed in v11.1.0

**Comment by Shyclops** [comment]
Haha

I might be in the minority, I found this when using dice roller on a table that changed each time I rolled it (I was simulating drawing a stone from a bag so I was removing an option each roll, or resetting the bag, was for 13th age and I'm a chaos mage so I don't get to pick the type of spell I cast)

Sent from Proton Mail Android

-------- Original Message --------

**Comment by Shyclops** [comment]
Technically it's done inside of obsidian but I guess meta-bind regex buttons don't count

Sent from Proton Mail Android

-------- Original Message --------
