### ISSUE TITLE
🐞 regression - table rollers - lookup table

### ISSUE THREAD

**Issue by tyrcho** [javalent/dice-roller#331]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

Using a lookup table should return an entry

### Current behaviour

No text is returned

![image](https://github.com/user-attachments/assets/c3fa9f2c-d0ae-4939-b7d2-b89265cc5fb3)

### Reproduction

Here is a simplified markdown file which reproduces the issue : 

`dice: [](Debug.md#^bete)`

| dice: 1d10 | Bête                         |
| ---------- | ---------------------------- |
| 1-7        | `dice: [](Debug^terrestre)`  |
| 8-10       | `dice: [](Debug.md#^aerien)` |
^bete

| Terrestre |
| --------- |
| puce      |
| tique     |
| pou       |
| escargot  |
^terrestre

| Aérien     |
| ---------- |
| moustique  |
| luciole    |
| sauterelle |
| libellule  |
^aerien

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.6.7 and 1.4.13

### Plugin Version

11.2.0

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

### Possible solution

This used to work before I update. 
On my android phone I'm on 11.0.4 and the same file behaves as expected.

**Comment by tyrcho** [comment]
Note that this 3 strings work as expected


`dice: [](Debug.md^terrestre)`

`dice: [](Debug^terrestre)`

`dice: [](Debug.md#^terrestre)`

**Comment by tyrcho** [comment]
I also tried to replace the lookup table definition, removing the dice column, with no effect


| Bête                           |
| ------------------------------ |
| `dice: [](Debug.md^terrestre)` |
| `dice: [](Debug.md^aerien)`    |
^bete

**Comment by tyrcho** [comment]
fixed with d8df63d27df6a6489436a40b6170e7c0f76569a6

**Comment by xgdgsc** [comment]
In my case , template using dice-mod not work while dice works.

**Comment by xgdgsc** [comment]
I have to return to 11.0.5.
