### ISSUE TITLE
🐞 dice-mod: doesn't execute when used as a section roller.

### ISSUE THREAD

**Issue by StalwartS0ul** [javalent/dice-roller#336]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

The command `dice-mod: [[Famous Quotes#^famous-quotes]]|Quote` should return the section from the table "Famous Quotes" under column "Quotes". 

The code block is correct. And Dice Roller is able to execute if the command is `dice: [[Famous Quotes#^famous-quotes]]|Quote`. And returns the "Quote" column as expected.

`dice-mod` does work as intended if I'm rolling for dice results only. i.e. `dice-mod: 1d4`

### Current behaviour

![1](https://github.com/user-attachments/assets/8ec2c1c6-adff-4a32-8fd3-d60b08d0e9be)
![2](https://github.com/user-attachments/assets/8676d741-fead-45c5-add2-64cbb0164c41)

The dice-mod acts as if it's only a code block and not a command.

### Reproduction

Create any new note and type the command `dice-mod: [[table^blockid]]|section`. It remains a code block.

### Which Operating Systems are you using?

- [X] Android
- [X] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.6.7

### Plugin Version

11.2.1

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by geochatz** [comment]
I have the same issue.

Dice Roller v11.3.2
Obsidian v1.6.7
on MacOS

**Comment by PhyberApex** [comment]
Same here

Dice Roller v11.3.2
Obsidian v1.6.7
on MacOS

**Comment by PhyberApex** [comment]
No longer broken with

Dice Roller v11.3.4
Obsidian v1.7.4
on MacOS

**Comment by StalwartS0ul** [comment]
Also fixed on Win11, iPadOS 18.1 and Android 15.

Dice Roller 11.3.4
Obsidian 1.7.4
