### ISSUE TITLE
Re-roll on line edits

### ISSUE THREAD

**Issue by geoffreysflaminglasersword** [javalent/dice-roller#37]
Even though the global save setting is enabled (which functions correctly when navigating between notes), if any line with a dice roller insert is edited in any way, all dice are re-rolled. This causes re-rolls on todo item toggles, as well as re-rolls if a paragraph of text is edited that contains an insert.
![DiceRollerIssue](https://user-images.githubusercontent.com/31261158/135357766-a2df2b80-c3e5-4a58-a26a-481254c0674e.gif)

**Comment by valentine195** [comment]
Just to make sure, this happens if you edit *any* line that a DR is on, not just if you click a checkbox?

**Comment by geoffreysflaminglasersword** [comment]
> Just to make sure, this happens if you edit _any_ line that a DR is on, not just if you click a checkbox?

Yes, any line

**Comment by geoffreysflaminglasersword** [comment]
I've both updated, and uninstalled/reinstalled, and I still have this issue

**Comment by valentine195** [comment]
Okay I’ll take a look. 

Is it just section, table and/or tag rollers re-rolling? (Not dice rolls like 1d4 etc)

**Comment by geoffreysflaminglasersword** [comment]
> Okay I’ll take a look.
> 
> Is it just section, table and/or tag rollers re-rolling? (Not dice rolls like 1d4 etc)

Yeah, it looks like normal dice rolls work just fine

**Comment by sigrunixia** [comment]
Closing due to the age between the last comment and now. If this is still an issue, a new request can be created.
