### ISSUE TITLE
Allow Note to be 'Source' of Dice Roller View

### ISSUE THREAD

**Issue by HAJ523** [javalent/dice-roller#62]
Allow selecting a specific note as the Dice Roller View Source. The field references used in the dice roller could pull from that note. (Ideally this selection would be in the dice roller to allow for on the fly transition to a new note source.)

**Comment by valentine195** [comment]
You can actually pin notes into the sidebar by dragging them there, I think this would cover this use case.

**Comment by HAJ523** [comment]
Into your rolling sidebar? That doesn't seem to work. How would the sidebar roller know to use that note as the container of the field values?

**Comment by valentine195** [comment]
Maybe I misunderstood what you want. I assume you wanted to include dice formulas that are saved in a note in the sidebar. You can just create a note with the rolls you want and drag the note into the sidebar

https://user-images.githubusercontent.com/38669521/149550003-83cb0a7a-e497-4898-92ac-33357f18d1a1.mp4

.

**Comment by HAJ523** [comment]
It seems we have a mis-understanding.

As part of the notes you state that rolls can have access note Dataview fields to for the dice. If you have this setup for something like a character sheet then setup a saved roll for something like 'Perception check' your saved roll could access the field data of the note specified as the default. This way when using different characters you could either select a new note and use the same saved rolls without necessarily having to have the note open.
