### ISSUE TITLE
Keep highest, unless condition

### ISSUE THREAD

**Issue by kdomke** [javalent/dice-roller#71]
Hi, 

In the german RPG Splittermond you have a very special roll. 

You roll 4d10 and keep the highest two, UNLESS you can somehow get 3 or less with two of the dice. 

e.g.:
rolled dice: 3 4 5 6 --> 5+6 = 11
rolled dice: 1 3 5 6 --> 5-6 = 11
rolled dice: 1 2 5 6 --> 1+2 = 3   <--- special case

Is it possible to create such a Roll with this plugin?

**Comment by valentine195** [comment]
It is not yet but should be possible to add. I’m trying to think of a good syntax for it. It will probably be chained `kh`… like:

`dice: 4d10kh2<=3kh2`

**Comment by sigrunixia** [comment]
This functionality was implemented
