### ISSUE TITLE
Wanted: Returning random number of elements from a table

### ISSUE THREAD

**Issue by shepster** [javalent/dice-roller#82]
Is it possible to pull, say 1d4 results from a random table?

```
| dice: 1d6 | item |
| --- | --- |
| 1-3 | Common |
| 4,5 | Rare |
| 6   | Unique |

^item

`dice: 1d4[[testing#^item]]`
```
So I would get either  1, 2, 3, or 4 results from the random table roll

**Comment by Zagor91** [comment]
I just made the random tables of "The Perilous Wild" by Lampblack & Brimstone and I have the same concern for the "Lookup Tables".

Here is a proposed syntax for rolling a dice different from that of the table:
`dice: [[testing#^item]] => [5] = > Rare`
`dice: [[testing#^item]]|dice:1d4+1 => [2]+1 = Common`

**Comment by ars-dev-br** [comment]
This has been implemented already with the syntax above, i.e.: `dice: 1d4+1[[Testing^table]]`.

**Comment by Zagor91** [comment]
> This has been implemented already with the syntax above, i.e.: `dice: 1d4+1[[Testing^table]]`.

The `dice: 1d4+1[[Note^block-id]]` syntax allows to return several elements but not to replace the dice of a Lookup Table.

For example, for the table:
| dice: 1d4 | Result |
| 1 | option 1 |
| 2 | option 2 |
| 3 | option 3 |
| 4 | option 4 |
^test

This formula `dice: [[ThisNote^test]]` reviews either option 1, option 2, option 3 or option 4

But the formula `dice: 1d1+1[[ThisNote^test]]` returns multiple elements, for example: option 2||option 4

I want to return from the table ThisNote^test not the result of the dice: 1d4 but another die roll: 1d2, for exemple with `dice: [[ThisNote^test]]|dice:1d2` must return either option 1 or option 2 but not option 3 or 4.

**Comment by sigrunixia** [comment]
Closing as this issue was implemented and Zagor made their own issue.
