### ISSUE TITLE
[Bug] `dice-mod` is broken in admonition blocks

### ISSUE THREAD

**Issue by Obsidian1212** [javalent/dice-roller#83]
![Screenshot_20220303-131102_Obsidian](https://user-images.githubusercontent.com/35908303/156500496-5ecf929b-b6da-4d4c-af9d-afafa3bc8a27.jpg)

![Screenshot_20220303-131038_Obsidian](https://user-images.githubusercontent.com/35908303/156500512-bc9bc518-c322-46d1-ae74-794e61466197.jpg)

The `dice-mod` there is treated as `dice` in the admonition block.

I can confirm that back at Admonitions version 6.10.1, this bug wasn't present.

(Maybe I should report this to the Admonitions repo... Hmmmmm)

**Comment by valentine195** [comment]
This is because of an old bug that I have yet to track down that affects post processors... if you disable and re-enable the Dice Roller plugin it should work again. Basically, nested processors have to be loaded after their containing processor or they won't perform as expected.

**Comment by sigrunixia** [comment]
While this is still present in live preview, this is a limitation of the live preview engine. Entering reader mode writes the dice to the note. The issues will presume to continue to get improve as Obsidian Updates.

Closing this thread.
