### ISSUE TITLE
Savage Worlds Wild Dice roll

### ISSUE THREAD

**Issue by jrens** [javalent/dice-roller#93]
I'm trying to setup a table to roll skills and can't figure out how to roll 2 different sided exploding dice and take the maximum of that. i.e. as a script example the behaviour would look like:
```
» ./roll.sh -de 1d8 1d6
d8: 1 = 1
d6: 6*, 3 = 9
9
```
If I do ```dice: 1d8! 1d6!``` the first roll always ends up stuck on whatever the initial roll value was, and it always takes the output of the second roll.

**Comment by valentine195** [comment]
This logic can’t be done, sorry, but I’ll think about it.

**Comment by sigrunixia** [comment]
Closing as this is a stale issue.
