### ISSUE TITLE
[Bug] Modifiers break dice keeping/dropping when using rendered dice. 

### ISSUE THREAD

**Issue by ColColonCleaner** [javalent/dice-roller#94]
Example: 2d20kh1 + 5
Example: 5 + 2d20dl

Expected Result: The lower dice is dropped, then 5 added to it.

Actual result: Both dice are added together (none are dropped), and then 5 is added to it.

Keeping/dropping works fine without modifiers, but as soon as a mod is added it stops working.

**Comment by ColColonCleaner** [comment]
@valentine195 Video of the issue https://www.youtube.com/watch?v=mtCXt7uuXcs

**Comment by ColColonCleaner** [comment]
Just played around with some of the settings and found a workaround. This only breaks when using the 'rendered' dice. If rendering is disabled then it drops/keeps dice correctly.

**Comment by JYCasalis** [comment]
Not sure I found the _exact_ fix but I'll submit a pull request so that Jeremy can double check.
