### ISSUE TITLE
[Bug] When 'always render dice' is enabled, the dice roller side-panel always rolls twice.

### ISSUE THREAD

**Issue by ColColonCleaner** [javalent/dice-roller#97]
When it's disabled there isn't any issue, but when 'Always Render Dice' is enabled the side-panel for rolling always throws two sets of dice across the screen and picks the 2nd set for the result.

**Comment by saif-ellafi** [comment]
Came to report this too

**Comment by sigrunixia** [comment]
This has long been fixed. If this issue is still a problem for some users, a new thread is needed.
